package com.twilio.src

class Constants {
  companion object {
    var PREF_NAME = "twilio_prefs"
    var PREF_TOEKN = "twilio_pref_token"
    var ON_FRAME_DIMENSIONS_CHANGED = "onFrameDimensionsChanged"
    var ON_CAMERA_SWITCHED = "onCameraSwitched"
    var ON_VIDEO_CHANGED = "onVideoChanged"
    var ON_AUDIO_CHANGED = "onAudioChanged"
    var ROOM_NAME = "roomName"
    var ROOM_SID = "roomSid"
    var PARTICIPANT_NAME = "participantName"
    var PARTICIPANT_SID = "participantSid"
    var PARTICIPANT = "participant"
    var PARTICIPANTS = "participants"
    var LOCAL_PARTICIPANT = "localParticipant"
    var TRACK = "track"
    var TRACK_SID = "trackSid"
    var TRACK_NAME = "trackName"
    var ENABLED = "enabled"
    var IDENTITY = "identity"
    var SID = "sid"
    var IS_LOCAL_USER = "isLocalUser"
    var QUALITY = "quality"
    var END_CALL = "endCall"
    var ERROR = "error"
    var ON_CONNECTED = "onRoomDidConnect"
    var ON_RE_CONNECTED = "onRoomReConnect"
    var ON_CONNECT_FAILURE = "onRoomDidFailToConnect"
    var ON_DISCONNECTED = "onRoomDidDisconnect"
    var ON_PARTICIPANT_CONNECTED = "onRoomParticipantDidConnect"
    var ON_PARTICIPANT_RECONNECTED = "onRoomParticipantReconnect"
    var ON_PARTICIPANT_DISCONNECTED = "onRoomParticipantDidDisconnect"
    var ON_DATATRACK_MESSAGE_RECEIVED = "onDataTrackMessageReceived"
    var ON_PARTICIPANT_ADDED_DATA_TRACK = "onParticipantAddedDataTrack"
    var ON_PARTICIPANT_REMOVED_DATA_TRACK = "onParticipantRemovedDataTrack"
    var ON_PARTICIPANT_ADDED_VIDEO_TRACK = "onParticipantAddedVideoTrack"
    var ON_PARTICIPANT_REMOVED_VIDEO_TRACK = "onParticipantRemovedVideoTrack"
    var ON_PARTICIPANT_ADDED_AUDIO_TRACK = "onParticipantAddedAudioTrack"
    var ON_PARTICIPANT_REMOVED_AUDIO_TRACK = "onParticipantRemovedAudioTrack"
    var ON_PARTICIPANT_ENABLED_VIDEO_TRACK = "onParticipantEnabledVideoTrack"
    var ON_PARTICIPANT_DISABLED_VIDEO_TRACK = "onParticipantDisabledVideoTrack"
    var ON_PARTICIPANT_ENABLED_AUDIO_TRACK = "onParticipantEnabledAudioTrack"
    var ON_PARTICIPANT_DISABLED_AUDIO_TRACK = "onParticipantDisabledAudioTrack"
    var ON_STATS_RECEIVED = "onStatsReceived"
    var ON_NETWORK_QUALITY_LEVELS_CHANGED = "onNetworkQualityLevelsChanged"
    var ON_DOMINANT_SPEAKER_CHANGED = "onDominantSpeakerDidChange"
    var ON_LOCAL_PARTICIPANT_SUPPORTED_CODECS = "onLocalParticipantSupportedCodecs"
  }
}
